### ISSUE TITLE
ToDo's for v0.2.0

### ISSUE THREAD

**Issue by GabrielSJones** [GabrielSJones/obs-mouse-overlay#1]
- [ ] Create installer for subsequent releases
- [ ] Add vector magnitude based display option
- [ ] Add general selection UI for input display options
  - [ ] Trail options
  - [ ] Color options (?)
  - [ ] Framerate (?)
  - [ ] Fix refresh/reset/apply button
- [ ] Update readme to include build steps
